/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_kesk_libgl_tools_GLES20Utils */

#ifndef _Included_fr_kesk_libgl_tools_GLES20Utils
#define _Included_fr_kesk_libgl_tools_GLES20Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_kesk_libgl_tools_GLES20Utils
 * Method:    glVertexAttribPointer
 * Signature: (IIIZII)V
 */
JNIEXPORT void JNICALL Java_fr_kesk_libgl_tools_GLES20Utils_glVertexAttribPointer
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     fr_kesk_libgl_tools_GLES20Utils
 * Method:    glDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_fr_kesk_libgl_tools_GLES20Utils_glDrawElements
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
