/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "matrix.h"
/* Header for class fr_kesk_libgl_tools_MatrixUtils */

#ifndef _Included_fr_kesk_libgl_tools_MatrixUtils
#define _Included_fr_kesk_libgl_tools_MatrixUtils
#ifdef __cplusplus
extern "C" {
#endif



#ifdef __cplusplus
}
#endif
#endif
