/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_kesk_libgl_tools_NodeUtils */

#ifndef _Included_fr_kesk_libgl_tools_NodeUtils
#define _Included_fr_kesk_libgl_tools_NodeUtils
#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif
#endif
